// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3KoSHwFX4GtJMFvPcja4p7CygiO9LCpg',
    appId: '1:594824420094:web:a516d81629cb5f6254a3af',
    messagingSenderId: '594824420094',
    projectId: 'csjmuhostel-e45f1',
    authDomain: 'csjmuhostel-e45f1.firebaseapp.com',
    databaseURL: 'https://csjmuhostel-e45f1-default-rtdb.firebaseio.com',
    storageBucket: 'csjmuhostel-e45f1.appspot.com',
    measurementId: 'G-612F8J4ZR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY-fO-JzFCo0eF9Iuv1uZtNa-E_LGGNfI',
    appId: '1:594824420094:android:aa8256ded7f07e0e54a3af',
    messagingSenderId: '594824420094',
    projectId: 'csjmuhostel-e45f1',
    databaseURL: 'https://csjmuhostel-e45f1-default-rtdb.firebaseio.com',
    storageBucket: 'csjmuhostel-e45f1.appspot.com',
  );
}
